return {
  'nvim-treesitter/nvim-treesitter',
  branch = 'main',
  build = ':TSUpdate',
  event = { 'BufRead', 'BufNewFile', 'InsertEnter' },
  config = function()
    require 'nvim-treesitter'.setup {}
    require 'nvim-treesitter'.install {
      'bash',
      'bibtex',
      'css',
      'diff',
      'editorconfig',
      'git_config',
      'git_rebase',
      'gitattributes',
      'gitcommit',
      'gitignore',
      'html',
      'javascript',
      'json',
      'julia',
      'kitty',
      'latex',
      'liquid',
      'lua',
      'luadoc',
      'luap',
      'make',
      'markdown',
      'markdown_inline',
      'perl',
      'python',
      'regex',
      'ruby',
      'toml',
      'vim',
      'vimdoc',
      'yaml',
    }
    vim.api.nvim_create_autocmd('FileType', {
      group = vim.api.nvim_create_augroup('vim-treesitter-start', {}),
      callback = function() pcall(vim.treesitter.start) end,
    })
  end,
}
