return {
  'nvim-treesitter/nvim-treesitter',
  event = { 'BufRead', 'BufNewFile', 'InsertEnter' },
  opts = {
    ensure_installed = {
      'bash',
      'bibtex',
      'diff',
      'git_config',
      'git_rebase',
      'gitattributes',
      'gitcommit',
      'gitignore',
      'html',
      'json',
      'julia',
      'latex',
      'lua',
      'luadoc',
      'make',
      'markdown',
      'markdown_inline',
      'perl',
      'python',
      'query',
      'r',
      'regex',
      'ruby',
      'rust',
      'toml',
      'typescript',
      'vim',
      'vimdoc',
      'yaml',
    },
    auto_install = false,
    ignore_install = {},
    sync_install = false,
    highlight = {
      enable = true,
      additional_vim_regex_highlighting = false,
    },
  },
}
