[battery]
disabled = true

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'
vimcmd_symbol = '[n](bold green)'
vimcmd_replace_one_symbol = '[v](bold purple)'
vimcmd_replace_symbol = '[R](bold purple)'
vimcmd_visual_symbol = '[v](bold yellow)'

[cmd_duration]
format = '[$duration]($style) '
style = 'yellow'

[directory]
truncation_length = 100
truncate_to_repo = false

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = 'red bold'
stashed = '\$'
ahead = '↑'
behind = '↓'
up_to_date = ''
diverged = '↕'
conflicted = '='
deleted = '✗'
renamed = '»'
modified = '!'
staged = '+'
untracked = '?'

[julia]
symbol = ' '

[lua]
symbol = ' '

[nodejs]
symbol = ' '

[python]
symbol = ' '

[ruby]
symbol = ' '

[rust]
symbol = ' '

[custom.html]
detect_extensions = ['html']
symbol = ' '

[custom.tex]
detect_extensions = ['tex']
symbol = ' '
