return {
  backspace = { 'indent', 'eol', 'start' },
  clipboard = { 'unnamed', 'unnamedplus' },
  fileencodings = 'utf-8',
  fileformats = { 'unix', 'dos', 'mac' },
  fillchars = { vert = ' ', fold = '·', eob = ' ' },
  gdefault = true,
  guicursor = { 'n-v-sm:block', 'i-c-ci-ve:ver25', 'r-cr-o:hor20' },
  helplang = { 'en', 'ja' },
  hidden = true,
  ignorecase = true,
  inccommand = 'split',
  infercase = true,
  laststatus = 2,
  listchars = { tab = '<·>', trail = '·', eol = '¬' },
  matchtime = 1,
  mouse = 'a',
  pumblend = 10,
  pumheight = 10,
  quickfixtextfunc = [[v:lua.require'qf'.textfunc]],
  ruler = false,
  scrolloff = 2,
  showmatch = true,
  showmode = false,
  smartcase = true,
  shortmess = {
    f = true,
    i = true,
    l = true,
    n = true,
    x = true,
    t = true,
    T = true,
    o = true,
    O = true,
    F = true,
    c = true,
  },
  splitbelow = true,
  splitright = true,
  tabline = [[%!v:lua.require'tabline'.tabline()]],
  termguicolors = true,
  title = true,
  viewoptions = { 'folds', 'cursor', 'curdir' },
  virtualedit = 'onemore',
  whichwrap = {
    b = true,
    s = true,
    ['<'] = true,
    ['>'] = true,
    ['['] = true,
    [']'] = true,
    ['~'] = true,
  },
  wildmenu = true,
  wildmode = { 'longest', 'full' },
  writebackup = false,

  expandtab = true,
  fileencoding = 'utf-8',
  shiftwidth = 0,
  smartindent = true,
  spell = false,
  spellfile = table.concat({
    vim.fn.stdpath 'data', 'spell', 'en.utf-8.add',
  }, '/'),
  spelllang = { 'en', 'cjk' },
  swapfile = false,
  tabstop = 2,

  breakindent = true,
  cursorline = false,
  foldcolumn = '2',
  foldtext = [[v:lua.require'fold'.foldtext()]],
  list = true,
  number = true,
  numberwidth = 5,
  relativenumber = true,
  signcolumn = 'yes:1',
  statusline = [[%!v:lua.require'statusline'.statusline()]],
  winblend = 10,
}
