#!/usr/bin/env perl

my @clean_exts = (
  '%R-blx.bib',
  'bbl',
  'bcf',
  'brf',
  'cb',
  'dvi',
  'fdb_latexmk',
  'fls',
  'glo',
  'hd',
  'nav',
  'nlo',
  'nls',
  'run',
  'run.xml',
  'snm',
  'synctex(busy)',
  'synctex.gz',
  'synctex.gz(busy)',
  'tdo',
  'tex.bak',
  'vrb',
);
$clean_ext = join(' ', @clean_exts);
$clean_full_ext = $clean_ext . 'bbl';

$opts = join(' ', (
    ' %O',
    '-file-line-error',
    '-halt-on-error',
    '-interaction=nonstopmode',
    '-synctex=1',
    '%S',
  ));
$latex = 'uplatex' . $opts;
$pdflatex = 'pdflatex' . $opts;
$lualatex = 'lualatex' . $opts;
$xelatex = 'xelatex' . $opts;

$dvipdf = 'dvipdfmx %O -o %D %S';

$pdf_mode = 3;

$bibtex = 'upbibtex %O %B';
$biber = 'biber --bblencoding=utf8 -u -U --output_safechars %O %B';

$makeindex = 'upmendex %O -o %D %S';

$max_repeat = 5;

$pdf_previewer = 'open -ga /Applications/Skim.app %S';

$pvc_view_file_via_temporary = 0;
